#! /bin/sh

# compositors and daemons

sxhkd &
picom &
dunst &

# workspaces

bspc monitor -d I II III IV V VI

# wallpaper

feh --bg-fill ~/Pictures/wallpapers/hand.png

# borders and gaps

bspc config border_width         0
bspc config window_gap          16

# advanced configuration of gaps

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# polybar

$HOME/.config/polybar/launch.sh

# pywal my beloved

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
