add_newline = false

format = """
[  $directory❯](bold #C9C6BA) """

[character]                            

#success_symbol = "[❯](bold green)"	

success_symbol = "[λ](bold blue)"

#success_symbol = "[❯](#ba8baf)[❯](bold green)[❯](#86c1b9)"

#success_symbol = "[♥](bold green) [♥](bold yellow) [♥](bold red) "     

#success_symbol = "[◗](bold red)[◗](bold yellow)[◗](bold green)"
 
